package com.code;

import static com.code.U4AdminAjuste.txt_u4_admin_ajuste_nombre_vigilante;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author luise
 */
public class U3AdminOpciones extends javax.swing.JFrame {

    private String u3CapturarNombresApellidos;

    public U3AdminOpciones() {
        initComponents();
        //--------------------------------------------------------------------------------------------------------|
        //METODO 01 Establece el título de la ventana principal
        this.setTitle("Sicovp Login Administración > Opciones");
        //--------------------------------------------------------------------------------------------------------| 
        //METODO 02 centrar la ventana actual del programa
        this.setLocationRelativeTo(null);
        //--------------------------------------------------------------------------------------------------------|    
        // Metodo 03 Confirmacion cerrar ventana actual: 
        //Configuramos la acción que sucede al hacer clic en el botón "X" de la ventana
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        // Agregamos un "window listener" que detecta cuando la ventana está siendo cerrada
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                // Mostramos un cuadro de diálogo para confirmar si el usuario desea cerrar la ventana
                int confirmed = JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas cerrar la ventana?", "Confirmación de cierre", JOptionPane.YES_NO_OPTION);
                // Si el usuario confirma que desea cerrar la ventana
                if (confirmed == JOptionPane.YES_OPTION) {
                    // Cerramos la ventana utilizando el método dispose()
                    dispose();
                }
            }
        });
        //--------------------------------------------------------------------------------------------------------|
    }
//--------------------------------------------------------------------------------------------------------|

//--------------------------------------------------------------------------------------------------------|    
//METODO 04 ICONO BARRA DE TAREAS
// Este método sobrescribe el método getIconImage de la clase JFrame para establecer el icono de la aplicación.
// El icono se carga desde el archivo ico_barratareas_1.png ubicado en el paquete com.iconos
// y se establece como el icono predeterminado para la ventana.
    @Override
    public Image getIconImage() {
        // Obtener la imagen del icono usando el recurso del archivo ico_barratareas_1.png
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("com/iconos/ico_barratareas_1.png"));
        // Devolver la imagen del icono para ser usada como el icono predeterminado para la ventana
        return retValue;
    }
//--------------------------------------------------------------------------------------------------------|
    // Este método se encarga de cerrar el JFrame actual, y mostrar otro

    private void metSetU4AdminAjuste() {
        U4AdminAjuste HALOID = new U4AdminAjuste();// Creamos una nueva instancia de la vista v1_adm_login  
        HALOID.setVisible(true);   // Hacemos visible la nueva vista
        this.dispose(); // Cerramos la vista actual
    }
//--------------------------------------------------------------------------------------------------------| 
    // Este método se encarga de cerrar el JFrame actual, y mostrar otro

    private void metSetV1Login() {
        U2LoginAdmon HALOID = new U2LoginAdmon();// Creamos una nueva instancia de la vista v1_adm_login  
        HALOID.setVisible(true);   // Hacemos visible la nueva vista
        this.dispose(); // Cerramos la vista actual
    }
//--------------------------------------------------------------------------------------------------------| 
//--------------------------------------------------------------------------------------------------------|  
//--------------------------------------------------------------------------------------------------------|  
//--------------------------------------------------------------------------------------------------------|  
//--------------------------------------------------------------------------------------------------------|  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_fondo = new javax.swing.JPanel();
        jPanel_fondo_baner = new javax.swing.JPanel();
        txt_fondo_baner = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCPanel1 = new com.bolivia.panel.JCPanel();
        txt_u3_nombre_vigilante = new javax.swing.JLabel();
        panelU3Opcion1 = new javax.swing.JPanel();
        txt_m_administrar1 = new javax.swing.JLabel();
        jCPanel_m_administrar1 = new com.bolivia.panel.JCPanel();
        panelU3Opcion2 = new javax.swing.JPanel();
        txt_m_administrar2 = new javax.swing.JLabel();
        jCPanel_m_administrar2 = new com.bolivia.panel.JCPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);

        jPanel_fondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_fondo.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel_fondo_baner.setBackground(new java.awt.Color(51, 51, 51));

        txt_fondo_baner.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_fondo_baner.setForeground(new java.awt.Color(255, 255, 255));
        txt_fondo_baner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_fondo_baner.setText("AJUSTES");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_home_x24.png"))); // NOI18N
        jButton1.setToolTipText("Regresar");
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_home_x20.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_home_x22.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jCPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jCPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jCPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_foto_perfil_hombre_x512.png"))); // NOI18N

        javax.swing.GroupLayout jCPanel1Layout = new javax.swing.GroupLayout(jCPanel1);
        jCPanel1.setLayout(jCPanel1Layout);
        jCPanel1Layout.setHorizontalGroup(
            jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jCPanel1Layout.setVerticalGroup(
            jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        txt_u3_nombre_vigilante.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txt_u3_nombre_vigilante.setForeground(new java.awt.Color(255, 255, 255));
        txt_u3_nombre_vigilante.setText("v1_ajuste_txt_get_name_vigilante");

        javax.swing.GroupLayout jPanel_fondo_banerLayout = new javax.swing.GroupLayout(jPanel_fondo_baner);
        jPanel_fondo_baner.setLayout(jPanel_fondo_banerLayout);
        jPanel_fondo_banerLayout.setHorizontalGroup(
            jPanel_fondo_banerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fondo_banerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(232, 232, 232)
                .addComponent(txt_fondo_baner, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_u3_nombre_vigilante)
                .addContainerGap())
        );
        jPanel_fondo_banerLayout.setVerticalGroup(
            jPanel_fondo_banerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fondo_banerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_fondo_banerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_fondo_banerLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(txt_fondo_baner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(txt_u3_nombre_vigilante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        panelU3Opcion1.setBackground(new java.awt.Color(204, 204, 204));
        panelU3Opcion1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelU3Opcion1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelU3Opcion1MouseMoved(evt);
            }
        });
        panelU3Opcion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelU3Opcion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelU3Opcion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelU3Opcion1MouseExited(evt);
            }
        });

        txt_m_administrar1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_m_administrar1.setText("Administrar Usuarios");

        jCPanel_m_administrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_add-user_x64.png"))); // NOI18N

        javax.swing.GroupLayout jCPanel_m_administrar1Layout = new javax.swing.GroupLayout(jCPanel_m_administrar1);
        jCPanel_m_administrar1.setLayout(jCPanel_m_administrar1Layout);
        jCPanel_m_administrar1Layout.setHorizontalGroup(
            jCPanel_m_administrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        jCPanel_m_administrar1Layout.setVerticalGroup(
            jCPanel_m_administrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelU3Opcion1Layout = new javax.swing.GroupLayout(panelU3Opcion1);
        panelU3Opcion1.setLayout(panelU3Opcion1Layout);
        panelU3Opcion1Layout.setHorizontalGroup(
            panelU3Opcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelU3Opcion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCPanel_m_administrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_m_administrar1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );
        panelU3Opcion1Layout.setVerticalGroup(
            panelU3Opcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelU3Opcion1Layout.createSequentialGroup()
                .addGroup(panelU3Opcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCPanel_m_administrar1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(txt_m_administrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelU3Opcion2.setBackground(new java.awt.Color(204, 204, 204));
        panelU3Opcion2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelU3Opcion2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelU3Opcion2MouseMoved(evt);
            }
        });
        panelU3Opcion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelU3Opcion2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelU3Opcion2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelU3Opcion2MouseExited(evt);
            }
        });

        txt_m_administrar2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_m_administrar2.setText("Sin programar");

        jCPanel_m_administrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_add-user_x64.png"))); // NOI18N

        javax.swing.GroupLayout jCPanel_m_administrar2Layout = new javax.swing.GroupLayout(jCPanel_m_administrar2);
        jCPanel_m_administrar2.setLayout(jCPanel_m_administrar2Layout);
        jCPanel_m_administrar2Layout.setHorizontalGroup(
            jCPanel_m_administrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        jCPanel_m_administrar2Layout.setVerticalGroup(
            jCPanel_m_administrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelU3Opcion2Layout = new javax.swing.GroupLayout(panelU3Opcion2);
        panelU3Opcion2.setLayout(panelU3Opcion2Layout);
        panelU3Opcion2Layout.setHorizontalGroup(
            panelU3Opcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelU3Opcion2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCPanel_m_administrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_m_administrar2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );
        panelU3Opcion2Layout.setVerticalGroup(
            panelU3Opcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelU3Opcion2Layout.createSequentialGroup()
                .addGroup(panelU3Opcion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCPanel_m_administrar2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(txt_m_administrar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_fondoLayout = new javax.swing.GroupLayout(jPanel_fondo);
        jPanel_fondo.setLayout(jPanel_fondoLayout);
        jPanel_fondoLayout.setHorizontalGroup(
            jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_fondo_baner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelU3Opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelU3Opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_fondoLayout.setVerticalGroup(
            jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                .addComponent(jPanel_fondo_baner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelU3Opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelU3Opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        /* ----------------------------------------------- Ini Boton (home)  ----------------------------------------------- */
        metSetV1Login();//Invocar metodo
        /* ----------------------------------------------- Fin Boton (home)  ----------------------------------------------- */
    }//GEN-LAST:event_jButton1MouseClicked

    private void panelU3Opcion1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelU3Opcion1MouseMoved
//──────────────────────────────────────────────────────────────────
//Evento MauseMoved (Al mover el cursos set color personalizado)
        panelU3Opcion1.setBackground(new Color(213, 219, 219));
//──────────────────────────────────────────────────────────────────
    }//GEN-LAST:event_panelU3Opcion1MouseMoved

    private void panelU3Opcion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelU3Opcion1MouseEntered

    }//GEN-LAST:event_panelU3Opcion1MouseEntered

    private void panelU3Opcion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelU3Opcion1MouseExited
//──────────────────────────────────────────────────────────────────
//Evento MauseExited(Al quitar el cursos set color default)
        panelU3Opcion1.setBackground(new Color(204, 204, 204));

//──────────────────────────────────────────────────────────────────
    }//GEN-LAST:event_panelU3Opcion1MouseExited

    private void panelU3Opcion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelU3Opcion1MouseClicked
        /* ----------------------------------------------- Ini Boton (Administrar)  ----------------------------------------------- */
        metSetU4AdminAjuste();//Invocar metodo
        /*A LA VARIANLE LE ASIGNAMOS LO QUE HAY EN txt_u3_nombre_vigilante */
        u3CapturarNombresApellidos = txt_u3_nombre_vigilante.getText();
        /*ENVIAMOS LA INFORMACION CAPTURADA A LA SIGUIENTE PAGINA*/
        txt_u4_admin_ajuste_nombre_vigilante.setText(u3CapturarNombresApellidos);
        /* ----------------------------------------------- Fin Boton (Administrar)  ----------------------------------------------- */
    }//GEN-LAST:event_panelU3Opcion1MouseClicked

    private void panelU3Opcion2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelU3Opcion2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelU3Opcion2MouseMoved

    private void panelU3Opcion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelU3Opcion2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelU3Opcion2MouseClicked

    private void panelU3Opcion2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelU3Opcion2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelU3Opcion2MouseEntered

    private void panelU3Opcion2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelU3Opcion2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelU3Opcion2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U3AdminOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U3AdminOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U3AdminOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U3AdminOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U3AdminOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.bolivia.panel.JCPanel jCPanel1;
    private com.bolivia.panel.JCPanel jCPanel_m_administrar1;
    private com.bolivia.panel.JCPanel jCPanel_m_administrar2;
    private javax.swing.JPanel jPanel_fondo;
    private javax.swing.JPanel jPanel_fondo_baner;
    private javax.swing.JPanel panelU3Opcion1;
    private javax.swing.JPanel panelU3Opcion2;
    private javax.swing.JLabel txt_fondo_baner;
    private javax.swing.JLabel txt_m_administrar1;
    private javax.swing.JLabel txt_m_administrar2;
    public static javax.swing.JLabel txt_u3_nombre_vigilante;
    // End of variables declaration//GEN-END:variables
}
