
package com.code;

/**
 *
 * @author luise
 */
public class U4AdminAjuste extends javax.swing.JFrame {

    /**
     * Creates new form U4AdminAjuste
     */
    public U4AdminAjuste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_fondo_baner = new javax.swing.JPanel();
        txt_fondo_baner = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCPanel1 = new com.bolivia.panel.JCPanel();
        v1_login_admon_ajuste_name_vigilante = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtU4NumeroCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtU4Nombres = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtU4Apellidos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtU4Correo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtU4Celular = new javax.swing.JTextField();
        jLabel_foto_perfil = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtU4Contraseña = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtU4FechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        cmbU4TipoUsuario = new javax.swing.JComboBox<>();
        btbU4Agregar = new javax.swing.JButton();
        btnU4Modificar = new javax.swing.JButton();
        btbU4Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAdmonAjustes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));

        jPanel_fondo_baner.setBackground(new java.awt.Color(51, 51, 51));

        txt_fondo_baner.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_fondo_baner.setForeground(new java.awt.Color(255, 255, 255));
        txt_fondo_baner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_fondo_baner.setText("                                             ADMINISTRADOR AJUSTES");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_home_x24.png"))); // NOI18N
        jButton1.setToolTipText("Regresar");
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_home_x20.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_home_x22.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jCPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jCPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jCPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_foto_perfil_hombre_x512.png"))); // NOI18N

        javax.swing.GroupLayout jCPanel1Layout = new javax.swing.GroupLayout(jCPanel1);
        jCPanel1.setLayout(jCPanel1Layout);
        jCPanel1Layout.setHorizontalGroup(
            jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jCPanel1Layout.setVerticalGroup(
            jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        v1_login_admon_ajuste_name_vigilante.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        v1_login_admon_ajuste_name_vigilante.setForeground(new java.awt.Color(255, 255, 255));
        v1_login_admon_ajuste_name_vigilante.setText("v1_ajuste_txt_get_name_vigilante");

        javax.swing.GroupLayout jPanel_fondo_banerLayout = new javax.swing.GroupLayout(jPanel_fondo_baner);
        jPanel_fondo_baner.setLayout(jPanel_fondo_banerLayout);
        jPanel_fondo_banerLayout.setHorizontalGroup(
            jPanel_fondo_banerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fondo_banerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_fondo_baner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v1_login_admon_ajuste_name_vigilante)
                .addContainerGap())
        );
        jPanel_fondo_banerLayout.setVerticalGroup(
            jPanel_fondo_banerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addComponent(v1_login_admon_ajuste_name_vigilante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_fondo_banerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_fondo_banerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fondo_baner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtU4NumeroCedula.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        txtU4NumeroCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtU4NumeroCedula.setText("1096239932");
        txtU4NumeroCedula.setMaximumSize(new java.awt.Dimension(200, 26));
        txtU4NumeroCedula.setMinimumSize(new java.awt.Dimension(200, 26));
        txtU4NumeroCedula.setPreferredSize(new java.awt.Dimension(200, 26));
        txtU4NumeroCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtU4NumeroCedulaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtU4NumeroCedulaFocusLost(evt);
            }
        });
        txtU4NumeroCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtU4NumeroCedulaActionPerformed(evt);
            }
        });
        txtU4NumeroCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtU4NumeroCedulaKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText(" Numero Cedula *");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText(" Nombres *");

        txtU4Nombres.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        txtU4Nombres.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtU4Nombres.setText("Luis Eduardo   ");
        txtU4Nombres.setMaximumSize(new java.awt.Dimension(200, 26));
        txtU4Nombres.setMinimumSize(new java.awt.Dimension(200, 26));
        txtU4Nombres.setPreferredSize(new java.awt.Dimension(200, 26));
        txtU4Nombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtU4NombresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtU4NombresFocusLost(evt);
            }
        });
        txtU4Nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtU4NombresActionPerformed(evt);
            }
        });
        txtU4Nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtU4NombresKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText(" Apellidos *");

        txtU4Apellidos.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        txtU4Apellidos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtU4Apellidos.setText("Morales Florez  ");
        txtU4Apellidos.setMaximumSize(new java.awt.Dimension(200, 26));
        txtU4Apellidos.setMinimumSize(new java.awt.Dimension(200, 26));
        txtU4Apellidos.setPreferredSize(new java.awt.Dimension(200, 26));
        txtU4Apellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtU4ApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtU4ApellidosFocusLost(evt);
            }
        });
        txtU4Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtU4ApellidosActionPerformed(evt);
            }
        });
        txtU4Apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtU4ApellidosKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText(" Correo Electronico *");

        txtU4Correo.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        txtU4Correo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtU4Correo.setText("luiseduardo192@hotmail.com");
        txtU4Correo.setMaximumSize(new java.awt.Dimension(200, 26));
        txtU4Correo.setMinimumSize(new java.awt.Dimension(200, 26));
        txtU4Correo.setPreferredSize(new java.awt.Dimension(200, 26));
        txtU4Correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtU4CorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtU4CorreoFocusLost(evt);
            }
        });
        txtU4Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtU4CorreoActionPerformed(evt);
            }
        });
        txtU4Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtU4CorreoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText(" # Celular *");

        txtU4Celular.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        txtU4Celular.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtU4Celular.setText("3202187288 ");
        txtU4Celular.setMaximumSize(new java.awt.Dimension(200, 26));
        txtU4Celular.setMinimumSize(new java.awt.Dimension(200, 26));
        txtU4Celular.setPreferredSize(new java.awt.Dimension(200, 26));
        txtU4Celular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtU4CelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtU4CelularFocusLost(evt);
            }
        });
        txtU4Celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtU4CelularActionPerformed(evt);
            }
        });
        txtU4Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtU4CelularKeyTyped(evt);
            }
        });

        jLabel_foto_perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText(" Contraseña *");

        txtU4Contraseña.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        txtU4Contraseña.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtU4Contraseña.setText("ParqueNatura2024");
        txtU4Contraseña.setMaximumSize(new java.awt.Dimension(200, 26));
        txtU4Contraseña.setMinimumSize(new java.awt.Dimension(200, 26));
        txtU4Contraseña.setPreferredSize(new java.awt.Dimension(200, 26));
        txtU4Contraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtU4ContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtU4ContraseñaFocusLost(evt);
            }
        });
        txtU4Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtU4ContraseñaActionPerformed(evt);
            }
        });
        txtU4Contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtU4ContraseñaKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText(" Fecha Nacimiento *");

        txtU4FechaNacimiento.setToolTipText("¡Ingrese su fecha de nacimiento!");
        txtU4FechaNacimiento.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText(" Tipo de Usuario *");

        cmbU4TipoUsuario.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        cmbU4TipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Administrador" }));
        cmbU4TipoUsuario.setToolTipText("¡Selecione el tipo de usuario!");

        btbU4Agregar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btbU4Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_agregar_usuario_40px.png"))); // NOI18N
        btbU4Agregar.setText("Agregar");
        btbU4Agregar.setPreferredSize(new java.awt.Dimension(123, 38));
        btbU4Agregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_agregar_usuario_32px.png"))); // NOI18N
        btbU4Agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_agregar_usuario_37px.png"))); // NOI18N
        btbU4Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbU4AgregarMouseClicked(evt);
            }
        });
        btbU4Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbU4AgregarActionPerformed(evt);
            }
        });

        btnU4Modificar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnU4Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_actualizar_usuario_40px.png"))); // NOI18N
        btnU4Modificar.setText("Modificar");
        btnU4Modificar.setPreferredSize(new java.awt.Dimension(123, 38));
        btnU4Modificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_actualizar_usuario_32px.png"))); // NOI18N
        btnU4Modificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_actualizar_usuario_37px.png"))); // NOI18N
        btnU4Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnU4ModificarMouseClicked(evt);
            }
        });
        btnU4Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnU4ModificarActionPerformed(evt);
            }
        });

        btbU4Eliminar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btbU4Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_eliminar_usuario_40px.png"))); // NOI18N
        btbU4Eliminar.setText("Eliminar");
        btbU4Eliminar.setPreferredSize(new java.awt.Dimension(123, 38));
        btbU4Eliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_eliminar_usuario_32px.png"))); // NOI18N
        btbU4Eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iconos/ico_eliminar_usuario_37px.png"))); // NOI18N
        btbU4Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbU4EliminarMouseClicked(evt);
            }
        });
        btbU4Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbU4EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel_foto_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(txtU4NumeroCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtU4Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtU4Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtU4Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtU4Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtU4Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtU4FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbU4TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btbU4Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnU4Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btbU4Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtU4NumeroCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtU4Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtU4Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtU4Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtU4Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtU4Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbU4TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtU4FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btbU4Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnU4Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btbU4Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel_foto_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTableAdmonAjustes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTableAdmonAjustes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_fondo_baner, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_fondo_baner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        /* ----------------------------------------------- Ini Boton (home)  ----------------------------------------------- */
//        metSetV1Ajuste();//Invocar metodo
//        //v1_ajuste_registro_capturar_nombre
//        v1_ajuste_registro_capturar_nombre = v1_ajuste_registro_name_vigilante.getText();//pedir nombres y guardarlo
//        v1_login_admon_ajuste_name_vigilante.setText(v1_ajuste_registro_capturar_nombre);//Enviar nombre guardado a otra ventana

        /* ----------------------------------------------- Fin Boton (home)  ----------------------------------------------- */
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtU4NumeroCedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4NumeroCedulaFocusGained

    }//GEN-LAST:event_txtU4NumeroCedulaFocusGained

    private void txtU4NumeroCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4NumeroCedulaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4NumeroCedulaFocusLost

    private void txtU4NumeroCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtU4NumeroCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4NumeroCedulaActionPerformed

    private void txtU4NumeroCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtU4NumeroCedulaKeyTyped
//        /* ------------------------------------------------------------------------------------ */
//        // Invocar LetterSpaceFilter
//        javax.swing.text.AbstractDocument doc
//        = (javax.swing.text.AbstractDocument) pivtxtget_nombre_visitante.getDocument();
//        doc.setDocumentFilter(new LetterSpaceFilter());
//        /* ------------------------------------------------------------------------------------ */
//        /* ------------------------------------------------------------------------------------ */
//        //Validador JtexField Cantidad de Caracteres deseados
//        if (pivtxtget_nombre_visitante.getText().length() == 35) {
//            evt.consume();
//        }
//        /* ------------------------------------------------------------------------------------ */
    }//GEN-LAST:event_txtU4NumeroCedulaKeyTyped

    private void txtU4NombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4NombresFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4NombresFocusGained

    private void txtU4NombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4NombresFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4NombresFocusLost

    private void txtU4NombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtU4NombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4NombresActionPerformed

    private void txtU4NombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtU4NombresKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4NombresKeyTyped

    private void txtU4ApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4ApellidosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4ApellidosFocusGained

    private void txtU4ApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4ApellidosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4ApellidosFocusLost

    private void txtU4ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtU4ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4ApellidosActionPerformed

    private void txtU4ApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtU4ApellidosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4ApellidosKeyTyped

    private void txtU4CorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4CorreoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4CorreoFocusGained

    private void txtU4CorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4CorreoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4CorreoFocusLost

    private void txtU4CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtU4CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4CorreoActionPerformed

    private void txtU4CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtU4CorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4CorreoKeyTyped

    private void txtU4CelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4CelularFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4CelularFocusGained

    private void txtU4CelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4CelularFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4CelularFocusLost

    private void txtU4CelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtU4CelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4CelularActionPerformed

    private void txtU4CelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtU4CelularKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4CelularKeyTyped

    private void txtU4ContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4ContraseñaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4ContraseñaFocusGained

    private void txtU4ContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtU4ContraseñaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4ContraseñaFocusLost

    private void txtU4ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtU4ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4ContraseñaActionPerformed

    private void txtU4ContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtU4ContraseñaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtU4ContraseñaKeyTyped

    private void btbU4AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbU4AgregarMouseClicked
        //Invocar metodos
//        metRegistrarIngresoVisitante();
    }//GEN-LAST:event_btbU4AgregarMouseClicked

    private void btbU4AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbU4AgregarActionPerformed

    }//GEN-LAST:event_btbU4AgregarActionPerformed

    private void btnU4ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnU4ModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnU4ModificarMouseClicked

    private void btnU4ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnU4ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnU4ModificarActionPerformed

    private void btbU4EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbU4EliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btbU4EliminarMouseClicked

    private void btbU4EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbU4EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbU4EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U4AdminAjuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U4AdminAjuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U4AdminAjuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U4AdminAjuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U4AdminAjuste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableAdmonAjustes;
    private javax.swing.JButton btbU4Agregar;
    private javax.swing.JButton btbU4Eliminar;
    private javax.swing.JButton btnU4Modificar;
    private javax.swing.JComboBox<String> cmbU4TipoUsuario;
    private javax.swing.JButton jButton1;
    private com.bolivia.panel.JCPanel jCPanel1;
    private com.bolivia.panel.JCPanel jCPanel2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_foto_perfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_fondo_baner;
    private javax.swing.JPanel jPanel_info_usuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtU4Apellidos;
    private javax.swing.JTextField txtU4Celular;
    private javax.swing.JTextField txtU4Contraseña;
    private javax.swing.JTextField txtU4Correo;
    private com.toedter.calendar.JDateChooser txtU4FechaNacimiento;
    private javax.swing.JTextField txtU4Nombres;
    private javax.swing.JTextField txtU4NumeroCedula;
    private javax.swing.JLabel txt_fondo_baner;
    public static javax.swing.JLabel v1_ajuste_registro_name_vigilante;
    public static javax.swing.JLabel v1_login_admon_ajuste_name_vigilante;
    // End of variables declaration//GEN-END:variables
}
